// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcCQ3oS_NirzGorT1bH97uMZLbamygws',
    appId: '1:846706377299:web:02fa2452d3b29cc291bca6',
    messagingSenderId: '846706377299',
    projectId: 'socialmedia-9836d',
    authDomain: 'socialmedia-9836d.firebaseapp.com',
    storageBucket: 'socialmedia-9836d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0TRzGsHB2l_fid8P2FeV7lciSfWrUK6M',
    appId: '1:846706377299:android:7383cc31b94af5ce91bca6',
    messagingSenderId: '846706377299',
    projectId: 'socialmedia-9836d',
    storageBucket: 'socialmedia-9836d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnV4xvs83nbwOvEKxv8lGXTZHKvHowx2Y',
    appId: '1:846706377299:ios:9412f8e39b61c75191bca6',
    messagingSenderId: '846706377299',
    projectId: 'socialmedia-9836d',
    storageBucket: 'socialmedia-9836d.appspot.com',
    iosClientId: '846706377299-kqb6fi6tour40g3111vlqbktg6d6jgus.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnV4xvs83nbwOvEKxv8lGXTZHKvHowx2Y',
    appId: '1:846706377299:ios:9412f8e39b61c75191bca6',
    messagingSenderId: '846706377299',
    projectId: 'socialmedia-9836d',
    storageBucket: 'socialmedia-9836d.appspot.com',
    iosClientId: '846706377299-kqb6fi6tour40g3111vlqbktg6d6jgus.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourse',
  );
}
